const state = {
  nim: null,
  netcall: null,
  sdk: false,
  chat: null,
  token: null,
  phone: null,
  name: null,
  id: null,
  oid: null,
  origin: null,
  paySet: null,
  card: {},
  publishObject: null,
  purpose: null,
  payedMoney: null,
  gapMoney: null,
  borrowId: null,
  usableMoney: null,
  credtiQuery: null,
  opinion: null,
  account: {},
  complianPhone: null,
  info: null,
  error: {
    modal: false,
    message: ''
  },
  iframe: null,
  bank: null,
  forget: null,
  wannaInfo: null,
  userInfo: null,
  chatObject: null,
  message: null,
  sessions: null,
  updatesession: null,
  friends: null,
  businessCard: null,
  messages: null,
  sessionId: null,
  loanTemplate: null,
  borrowType: null,
  blackList: [], // 黑名单
  verifyMessage: null,
  sysMsgUnread: null, // 系统通知未读数
  customMsg: null // 自定义消息
}
module.exports = state
